apiVersion: 1

deleteDatasources:
  - name: Prometheus
    type: prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
  - name: Neo4j
    type: grafana-neo4j-datasource
    access: proxy
    url: bolt://neo4j:7687
    jsonData:
      username: neo4j
    secureJsonData:
      password: ${NEO4J_PASSWORD}
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ai_agent_user
    database: ${POSTGRES_DB}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
