global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'n8n'
    metrics_path: /metrics
    static_configs:
      - targets: ['n8n:5678']

  # Additional static targets managed via file_sd
  - job_name: 'static-file-sd'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/static-targets.yml

  # Loki metrics
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  # RabbitMQ Prometheus endpoint (requires rabbitmq_prometheus plugin)
  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']

  # Promtail metrics
  - job_name: 'promtail'
    metrics_path: /metrics
    static_configs:
      - targets: ['promtail:9080']

  # Node Exporter: enable when node_exporter service is running
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # OpenTelemetry Collector metrics (enable when otel-collector is running)
  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8888']
