# Optional OTEL Collector compose override
# Usage: docker compose -f docker-compose.yml -f docker-compose.otel.yml up -d otel-collector

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.97.0
    container_name: otel-collector
    command: ["--config=/etc/otel/collector.yaml"]
    volumes:
      - ./infrastructure/monitoring/otel/collector.yaml:/etc/otel/collector.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Collector own Prometheus metrics
    networks:
      - enhanced-ai-network
    restart: unless-stopped

networks:
  enhanced-ai-network:
    external: true
